### ISSUE TITLE
Switch Screen

### ISSUE THREAD

**Issue by RaphxelS** [alejodaraio/lost-ark-map#1]
Hello,
is there any way to change the screen on which the map is displayed?
Thank you

**Comment by alejodaraio** [comment]
Something what we can do is add a setting to turn on/off the full screen then the user will be able to drag the window to another screen.

**Comment by RaphxelS** [comment]
I would be very grateful. I am not in a hurry at all, I use your app as is and it has been a great help, thank you.

**Comment by alejodaraio** [comment]
Updated on https://github.com/alejodaraio/lost-ark-map/releases/tag/v1.0.1
